"""Power Stone 2 held-item dictionary (generated by gen_dict.py from the game's own
item table @0x0C273900 + name table @0x0C29DDD0). Key = item CODE byte read at
(F+0x54 pointer) - 4 + 0x420 (low byte). code = item_no + 1. Codes >= 0xC1 are
stage objects (see STAGE_CODES)."""

# code: (name, category, range_class, thrown_on_use, initial_counter, counter_kind)
ITEMS = {
    0x01: ('Gun', 'ranged', 'ranged_long', False, 6, 'shots'),
    0x02: ('Bazooka', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x03: ('Flame Thrower', 'ranged', 'ranged_short', False, 220, 'frames'),
    0x04: ('Hammer', 'melee', 'melee_short', False, 600, 'frames'),
    0x05: ('Sword', 'melee', 'melee_short', False, 600, 'frames'),
    0x06: ('Power Sword', 'melee', 'melee_short', False, 600, 'frames'),
    0x07: ('Iron Pipe', 'melee', 'melee_short', False, 600, 'frames'),
    0x08: ('Small Bomb', 'explosive', 'throw', True, 420, 'fuse_frames'),
    0x09: ('Medium Bomb', 'explosive', 'throw', True, 420, 'fuse_frames'),
    0x0A: ('Large Bomb', 'explosive', 'throw', True, 420, 'fuse_frames'),
    0x0B: ('Fire-Bottle', 'explosive', 'throw', True, 10, 'unused(10)'),
    0x0C: ('Machine Gun', 'ranged', 'ranged_long', False, 25, 'shots'),
    0x0D: ('Ray Gun', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x0E: ('Magic Stick', 'melee', 'melee_long', False, 420, 'frames'),
    0x0F: ('Power Shield', 'shield', 'melee', False, 420, 'frames'),
    0x10: ('Apple', 'food', 'none', False, 45, 'heal?'),
    0x11: ('Short Cake', 'food', 'none', False, 55, 'heal?'),
    0x12: ('Meat', 'food', 'none', False, 115, 'heal?'),
    0x13: ('Flame Sword', 'melee', 'melee_long', False, 600, 'frames'),
    0x14: ('Ice Sword', 'melee', 'melee_short', False, 480, 'frames'),
    0x15: ('Thunder Sword', 'melee', 'melee_short', False, 480, 'frames'),
    0x16: ('Dragon Slayer', 'melee', 'melee_long', False, 600, 'frames'),
    0x17: ('Legendary Sword', 'melee', 'melee_long', False, 420, 'frames'),
    0x18: ('Frozen Tuna', 'melee', 'melee_long', False, 600, 'frames'),
    0x19: ('Umbrella', 'melee', 'melee_long', False, 600, 'frames'),
    0x1A: ('Deluxe Umbrella', 'melee', 'melee_long', False, 660, 'frames'),
    0x1B: ('Cheap Umbrella', 'melee', 'melee_long', False, 480, 'frames'),
    0x1C: ('Tranquilizer Gun', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x1D: ('Toy Hammer', 'melee', 'melee_short', False, 600, 'frames'),
    0x1E: ('Pickaxe', 'melee', 'melee_short', False, 600, 'frames'),
    0x1F: ('Magical Mallet', 'melee', 'melee_short', False, 420, 'frames'),
    0x20: ('Gigantic Hammer', 'melee', 'melee_long', False, 480, 'frames'),
    0x21: ('Soap Bubble Gun', 'ranged', 'ranged_short', False, 250, 'frames'),
    0x22: ('Homing Missile', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x23: ('Fire Cracker', 'explosive', 'throw', True, 10, 'unused(10)'),
    0x24: ('Leg Weight', 'throwable', 'throw', True, 10, 'unused(10)'),
    0x25: ('Deluxe Shield', 'shield', 'melee', False, 480, 'frames'),
    0x26: ('Spear', 'melee', 'melee_long', False, 420, 'frames'),
    0x27: ('Deluxe Spear', 'melee', 'melee_long', False, 420, 'frames'),
    0x28: ('Beam Gun', 'ranged', 'ranged_long', False, 8, 'shots'),
    0x29: ('Powerful Buster', 'ranged', 'ranged_long', False, 4, 'shots'),
    0x2A: ('Arm Gun', 'ranged', 'ranged_long', False, 8, 'shots'),
    0x2B: ('Battlefield Axe', 'melee', 'melee_short', False, 600, 'frames'),
    0x2C: ('Victory Axe', 'melee', 'melee_long', False, 600, 'frames'),
    0x2D: ("Lumber Jack's Axe", 'melee', 'melee_short', False, 600, 'frames'),
    0x2E: ("Brave Man's Axe", 'melee', 'melee_long', False, 480, 'frames'),
    0x2F: ('Big Racket', 'melee', 'melee_short', False, 600, 'frames'),
    0x30: ('Trident', 'melee', 'melee_long', False, 480, 'frames'),
    0x31: ('Deluxe Trident', 'melee', 'melee_long', False, 480, 'frames'),
    0x32: ('Fork', 'melee', 'melee_long', False, 420, 'frames'),
    0x33: ('3-Way Shotgun', 'ranged', 'ranged_long', False, 7, 'shots'),
    0x34: ('5-Way Shotgun', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x35: ('Leg Trap', 'trap', 'throw', True, 10, 'unused(10)'),
    0x36: ('Bamboo Shoot', 'trap', 'throw', True, 10, 'unused(10)'),
    0x37: ('Pitfall Hoop', 'trap', 'throw', True, 10, 'unused(10)'),
    0x38: ('Flame Rod', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x39: ('Ice Rod', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x3A: ('Thunder Rod', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x3B: ('Magic Rod', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x3C: ('Mystic Rod', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x3D: ('Weird Rod', 'ranged', 'ranged_long', False, 5, 'shots'),
    0x3E: ('Adhesive Spray', 'ranged', 'ranged_short', False, 4, 'shots'),
    0x3F: ('Medusa', 'shield', 'melee', False, 420, 'frames'),
    0x40: ('Petrifier', 'throwable', 'throw', True, 10, 'unused(10)'),
    0x41: ('Transparentizer', 'throwable', 'throw', True, 10, 'unused(10)'),
    0x42: ('Trumpet', 'ranged', 'ranged_short', False, 5, 'shots'),
    0x43: ('Loudspeaker', 'ranged', 'ranged_short', False, 5, 'shots'),
    0x44: ('Devil Sickle', 'melee', 'melee_short', False, 420, 'frames'),
    0x45: ('Morning Star', 'melee', 'melee_long', False, 600, 'frames'),
    0x46: ('Skateboard', 'mount', 'none', False, 600, 'frames'),
    0x47: ('Inline Skate', 'mount', 'none', False, 600, 'frames'),
    0x48: ('Scooter', 'mount', 'none', False, 600, 'frames'),
    0x49: ('Stick Bomb', 'explosive', 'throw', True, 10, 'unused(10)'),
    0x4A: ('Angel Wing', 'mount', 'none', False, 600, 'frames'),
    0x4B: ('Meteor', 'ranged', 'ranged_long', False, 10, 'shots'),
    0x4C: ('Typhoon', 'ranged', 'ranged_short', False, 10, 'shots'),
    0x4D: ('Fireworks', 'ranged', 'ranged_long', False, 10, 'shots'),
    0x4E: ('Beehive', 'explosive', 'throw', True, 10, 'unused(10)'),
    0x4F: ('Fire Dragon', 'creature', 'mid', False, 400, 'frames'),
    0x50: ('Ice Dragon', 'creature', 'mid', False, 400, 'frames'),
    0x51: ('Thunder Dragon', 'creature', 'mid', False, 400, 'frames'),
    0x52: ('Panther', 'creature', 'mid', False, 480, 'frames'),
    0x53: ('Rice Ball', 'food', 'none', False, 95, 'heal?'),
    0x54: ('Banana', 'food', 'none', False, 85, 'heal?'),
    0x55: ('Hamburger', 'food', 'none', False, 90, 'heal?'),
    0x56: ('Roast Chicken', 'food', 'none', False, 180, 'heal?'),
    0x57: ('Roast Pork', 'food', 'none', False, 200, 'heal?'),
    0x58: ('Wedding Cake', 'food', 'none', False, 125, 'heal?'),
    0x59: ('Rabbit Ear', 'wearable', 'none', False, 10, 'unused(10)'),
    0x5A: ('Rabbit Tail', 'wearable', 'none', False, 10, 'unused(10)'),
    0x5B: ('Rabbit Arm', 'wearable', 'none', False, 10, 'unused(10)'),
    0x5C: ('Rabbit Paw', 'wearable', 'none', False, 10, 'unused(10)'),
    0x5D: ('Cat Ear', 'wearable', 'none', False, 10, 'unused(10)'),
    0x5E: ('Cat Tail', 'wearable', 'none', False, 10, 'unused(10)'),
    0x5F: ('Cat Arm', 'wearable', 'none', False, 10, 'unused(10)'),
    0x60: ('Crown', 'wearable', 'none', False, 10, 'unused(10)'),
    0x61: ('Silk Hat', 'wearable', 'none', False, 10, 'unused(10)'),
    0x62: ('Straw Hat', 'wearable', 'none', False, 10, 'unused(10)'),
    0x63: ('Party Hat', 'wearable', 'none', False, 10, 'unused(10)'),
    0x64: ('Exciting Book', 'throwable', 'throw', True, 10, 'unused(10)'),
    0x65: ('Spoon', 'melee', 'melee_short', False, 420, 'frames'),
    0x66: ('Beam Sword', 'melee', 'melee_short', False, 600, 'frames'),
    0x67: ('Devil Tail', 'wearable', 'none', False, 10, 'unused(10)'),
    0x68: ('Cheese', 'food', 'none', False, 75, 'heal?'),
    0x69: ('Metallic Bat', 'melee', 'melee_short', False, 600, 'frames'),
    0x6A: ('Harisen', 'melee', 'melee_short', False, 600, 'frames'),
    0x6B: ('Hand Grenade', 'explosive', 'throw', True, 420, 'fuse_frames'),
    0x6C: ('Wind-Up Key', 'wearable', 'none', False, 10, 'unused(10)'),
    0x6D: ('Flower', 'wearable', 'none', False, 10, 'unused(10)'),
    0x6E: ('Cat Paw', 'wearable', 'none', False, 10, 'unused(10)'),
    0x6F: ('Shoes of Achilles', 'wearable', 'none', False, 10, 'unused(10)'),
    0x70: ('Bracelet', 'wearable', 'none', False, 10, 'unused(10)'),
    0x71: ("Emperor's Crown", 'wearable', 'none', False, 10, 'unused(10)'),
    0x72: ('Thumbtack', 'trap', 'throw', True, 10, 'unused(10)'),
    0x73: ('Power Stone Magazine', 'throwable', 'throw', True, 10, 'unused(10)'),
    0x74: ('Lance of Lava', 'ranged', 'ranged_long', False, 3, 'shots'),
    0x75: ('Light Stone', 'wearable', 'none', False, 10, 'unused(10)'),
    0x76: ('Plaster', 'wearable', 'none', False, 10, 'unused(10)'),
    0x77: ('Punching Gloves', 'wearable', 'none', False, 10, 'unused(10)'),
}

# codes seen held live (initial counter matched the game table) -- the rest are named
# from the game's own name table via code = item_no + 1 (proven by the 30 live matches)
LIVE_CONFIRMED = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x13, 0x19, 0x1D, 0x21, 0x24, 0x2B, 0x30, 0x33, 0x35, 0x39, 0x3B, 0x43, 0x44, 0x46, 0x6A}

# Stage objects share the type byte space above the items. On DESERT (all three training
# savestates) only 0xC3 and 0xC8 are holdable. Codes 0xC4.. are reused per stage.
STAGE_CODES = {
    0xC1: ("power stone", "not holdable via F+0x54"),
    0xC2: ("treasure chest", "not holdable"),
    0xC3: ("desert barrel cactus (stage prop)", "throwable, counter 10 unused"),
    0xC8: ("desert tall saguaro (stage prop)", "uproot/carry/throw, counter 10 unused"),
    0xC4: ("stage-specific: boat-stage turret (fn 0x0C0E455E, counter 30 per use, holder state 18) / airship object (fn 0x0C0D1BAE)", "GUESS"),
    0xC5: ("stage-specific throwable (fn 0x0C0DF0CA)", "GUESS"),
    0xCC: ("stage-specific (fn 0x0C0E5522, counter 600)", "GUESS"),
}

# ---------------------------------------------------------------- readers
OBJ_TYPE = 0x420     # u8 type code (this dict's key)
OBJ_STATE = 0x421    # u8: 0 pop-out, 2 resting, 5 held, 6 dropped/tossed, 7 held+in use, 8 thrown in flight, 10/11 dying
OBJ_COUNTER = 0x424  # u16 remaining shots / frames / fuse (see counter_kind)
OBJ_HOLDER_MASK = 0x426  # u8 1<<seat of the current holder (LIKELY)


def held_record(ram, f_anchor_guest):
    """ram = 16 MiB SYSTEM_RAM numpy view; f_anchor_guest = ps2_addr.GEMS[k][1].
    Returns record offset into ram (F+0x54 pointer - 4) or None."""
    o = (f_anchor_guest & 0xFFFFFF) + 0x54
    p = int(ram[o]) | int(ram[o+1]) << 8 | int(ram[o+2]) << 16 | int(ram[o+3]) << 24
    return ((p - 4) & 0xFFFFFF) if p else None


def held_item(ram, f_anchor_guest):
    """-> (code, name, category, range_class, thrown_on_use, counter, counter_frac) or None."""
    r = held_record(ram, f_anchor_guest)
    if r is None:
        return None
    code = int(ram[r + OBJ_TYPE])
    ctr = int(ram[r + OBJ_COUNTER]) | int(ram[r + OBJ_COUNTER + 1]) << 8
    if code in ITEMS:
        n, cat, rng, thrown, init, kind = ITEMS[code]
        frac = min(1.0, ctr / init) if kind in ("shots", "frames", "fuse_frames") and init else 1.0
        return code, n, cat, rng, thrown, ctr, frac
    if code >= 0xC1:
        return code, STAGE_CODES.get(code, ("stage object", ""))[0], "stage_prop", "throw", True, ctr, 1.0
    return code, "?", "unknown", "none", False, ctr, 1.0
